# Generated by Django 4.0.4 on 2022-05-13 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descrition', models.TextField()),
                ('image', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
                ('url', models.CharField(max_length=200)),
                ('repository', models.CharField(max_length=200)),
                ('tags', models.ManyToManyField(blank=True, to='base.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=2)),
                ('image', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
                ('address', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('cv', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images')),
                ('github', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
